const Product = [
    {
        id:1,
        img:"https://akam.cdn.jdmagicbox.com/images/icons/newwap/newhotkey/weddinghotkey.gif?w=48&q=75",
        title:"Wedding"
    },
    {
        id:2,
        img:"https://akam.cdn.jdmagicbox.com/images/icons/newwap/newhotkey/restaurant-2022.svg?w=48&q=75",
        title:"Restaurant"
    },{
        id:3,
        img:"https://akam.cdn.jdmagicbox.com/images/icons/newwap/newhotkey/hotel-2022.svg?w=48&q=75",
        title:"Hotels"
    },
    {
        id:4,
        img:"https://akam.cdn.jdmagicbox.com/images/icons/newwap/newhotkey/beauty.svg?w=48&q=75",
        title:"Beauty Spa"
    },
    {
        id:5,
        img:"https://akam.cdn.jdmagicbox.com/images/icons/newwap/newhotkey/homedecor.svg?w=48&q=75",
        title:"Homede coration"
    },
    {
        id:6,
        img:"https://akam.cdn.jdmagicbox.com/images/icons/newwap/newhotkey/education.svg?w=48&q=75",
        title:"Education"
    },
    {
        id:7,
        img:"https://akam.cdn.jdmagicbox.com/images/icons/newwap/newhotkey/renthire.svg?w=48&q=75",
        title:"Rent & Hire"
    },
    {
        id:8,
        img:"https://akam.cdn.jdmagicbox.com/images/icons/newwap/newhotkey/hospital_2023.svg?w=48&q=75",
        title:"Hospital"
    },
    {
        id:9,
        img:"https://akam.cdn.jdmagicbox.com/images/icons/newwap/newhotkey/contractor-2022.svg?w=48&q=75",
        title:"Contractor"
    },
    {
        id:10,
        img:"https://akam.cdn.jdmagicbox.com/images/icons/newwap/newhotkey/courier_2023.svg?w=48&q=75",
        title:"Courier"
    },
    {
        id:11,
        img:"https://akam.cdn.jdmagicbox.com/images/icons/newwap/newhotkey/packers_movers_2023.svg?w=48&q=75",
        title:"Packers"
    },
    ,
    {
        id:12,
        img:"https://akam.cdn.jdmagicbox.com/images/icons/newwap/newhotkey/driving_school_2023.svg?w=48&q=75",
        title:"Driving School"
    },
    {
        id:13,
        img:"https://akam.cdn.jdmagicbox.com/images/icons/newwap/newhotkey/eventorganizers.svg?w=48&q=75",
        title:"Event Organizers"
    },
    {
        id:14,
        img:"https://akam.cdn.jdmagicbox.com/images/icons/newwap/newhotkey/consultants_2023.svg?w=48&q=75",
        title:"Consultants_2023"
    },
    {
        id:15,
        img:"https://akam.cdn.jdmagicbox.com/images/icons/newwap/newhotkey/gym_2023.svg?w=48&q=75",
        title:"Gym"
    },
    {
        id:16,
        img:"https://akam.cdn.jdmagicbox.com/images/icons/newwap/newhotkey/dentist_2023.svg?w=48&q=75",
        title:"Dentist_2023"
    },
    {
        id:17,
        img:"https://akam.cdn.jdmagicbox.com/images/icons/newwap/newhotkey/restaurant-2022.svg?w=48&q=75",
        title:"Restaurant"
    },
    {
        id:18,
        img:"https://akam.cdn.jdmagicbox.com/images/icons/newwap/newhotkey/estate-agent.svg?w=48&q=75",
        title:"Estate Agents"
    },
    {
        id:19,
        img:"https://akam.cdn.jdmagicbox.com/images/icons/newwap/newhotkey/pg-hostels-rooms.svg?w=48&q=75",
        title:"Pg Hotels"
    },
    {
        id:20,
        img:"https://akam.cdn.jdmagicbox.com/images/icons/newwap/newhotkey/gym_2023.svg?w=48&q=75",
        title:"Gym"
    }
]
export {Product}